### PR TITLE
added support for youtube parameters in URL

### PR DESCRIPTION
**Pull request by mschinwald**
Youtube parameters like "start" are being cut off when the iframe is created. I wanted to add the start parameter to the URL to let the video start at a specific time. So the URL looks like this: https://youtu.be/1UdI_eoDPKQ?start=18

In this pull request I changed the code so that all the parameters in the URL are added to the iframe src.

### CODE REVIEW

**Comment by sachinchoolur** [comment]
Hey @mschinwald ,
Thank you for the PR.
This does not work with all the URLs. Please take a look at the example - https://regex101.com/r/gN7bO0/14

Can we change the regex slightly to get all the query parameters except the video id? 
Something like this - https://regex101.com/r/gN7bO0/15 ?

**Comment by mschinwald** [comment]
Hi @sachinchoolur,
you are right, I forgot that there are different versions of youtube URLs.

I think the regex from your link will work fine.

Can you just change the regex in the code or do I have to change it in my fork?

**Comment by sachinchoolur** [comment]
Sure, I can change the regex and update the PR

**Comment by dantahoua** [comment]
Hello! What is the status of this, I need to pass the time for the start of a youtube video. 
Something like: https://youtu.be/pWlk1gLkF2Y?t=95

**Comment by sachinchoolur** [comment]
Hey @dantahoua,
I'm sorry,  I forgot to update the PR during the v2 release. The next lightGallery release will be majorly focused on the video module improvements and I'll try to include the option to pass youtube params as well.

For now, you can update the start time using lightGallery events  
https://www.lightgalleryjs.com/docs/events/

```js
document
  .getElementById("gallery-container")
   // based on your requiremnts, use the appropriate event 
  .addEventListener("lgAfterOpen", (event) => {
    setTimeout(() => {
      const iframe = document.querySelector(".lg-video-object");
      iframe.setAttribute(
        "src",
        iframe
          .getAttribute("src")
          .replace("enablejsapi=1", "enablejsapi=1&start=45")
      );
    }, 100);
  }); 

```



Codepen  demo  https://codepen.io/sachinchoolur/pen/ExXxqPe

**Comment by dantahoua** [comment]
Thanks! perfect! :) Can't wait to the next release! :)

**Comment by sachinchoolur** [comment]
Hey @dantahoua ,
URL parameters is now available in version  [2.3.0-beta](https://github.com/sachinchoolur/lightGallery/releases/tag/2.3.0-beta)

@mschinwald,
Thank you so much for your contribution. Really sorry for not responding on time

**Pull request closed without merging**
