### PR TITLE
Added refresh method.

### PR DESCRIPTION
**Pull request by codealchemist**
Refreshes lightGallery after adding more content to the page.

### CODE REVIEW

**Comment by sachinchoolur** [comment]
Hi @codealchemist,
Thank you for your time and effort. I am not sure how feasible this solution is. It might break lightgallery modules and other functionalities.
Anyway, this can be done easily by using lightgallery methods. http://sachinchoolur.github.io/lightGallery/demos/methods.html

**Comment by codealchemist** [comment]
I have that change already working here:
https://atgallery.herokuapp.com/gallery/BestEarthPix

I tried using `destroy` but probably I missed passing `true` because it didn't work, not sure.
I'll try that again later.
Thanks for the reply @sachinchoolur!

**Comment by makshh** [comment]
@codealchemist You're right, very strange.

**Comment by codealchemist** [comment]
I tested using destroy and then calling lightgallery again to refresh the gallery.
The problem I've found is that if you click on an image before the gallery fully finishes loading the modal gets automatically closed when the initialization finishes.
That problem is not present with the refresh approach I've shared.

Is there a known workaround to avoid closing the image modal after refreshing the gallery?

**Comment by sachinchoolur** [comment]
I think you are calling `destroy` method when the gallery is open. In this case, you have to check the open state of the gallery and call `destroy` method only if the gallery is not open. 
Then listen for lightgallery close event and destroy and re-initialize if new items are added to the list.

Something like this 
``` javascript
var $el= $('#el');
var destroyGallery = false;
var slide = '<a href="img/img2.jpg">' +
    '<img src="img/thumb2.jpg" />' +
'</a>';
 
$el.lightGallery();
$('#appendSlide').on('click', function() {
    $el.append(slide);

    // Gallery is open
    if($('body').hasClass('lg-on')) {
        destroyGallery = true;
    } else {
        $el.data('lightGallery').destroy(true);
        $el.lightGallery();
    }
});

$el.on('onCloseAfter.lg', function(){
    if (destroyGallery) {
        $el.data('lightGallery').destroy(true);
        $el.lightGallery();
        destroyGallery = false;
    }
});
```

**Comment by codealchemist** [comment]
Thanks for your fast response @sachinchoolur!
:)

**Pull request closed without merging**
