### PR TITLE
Add fallback to src

### PR DESCRIPTION
**Pull request by JSteunou**
I'm in a case I do not handle the HTML and cannot add `data-src` to `img` so a fallback to `src` would be appreciated ;)

### CODE REVIEW

**Comment by JSteunou** [comment]
@sachinchoolur any news on this one? (and its baby brother https://github.com/sachinchoolur/lg-thumbnail/issues/1)

**Comment by sachinchoolur** [comment]
@JSteunou, 
I'm really sorry for the delayed response. Could you please provide an example, when this feature is useful?

**Comment by JSteunou** [comment]
I'm in a case where I have just a list of `` on a typical html web page without possibility to add `data-src` or wrap into a `<a>`

**Comment by sachinchoolur** [comment]
@JSteunou, 
I'm sorry, I think it is a very rare scenario and this feature won't be useful for most of the users.
Thank you so much for your contributions and guidance so far.

**Comment by JSteunou** [comment]
So you think all the users using this library on a blog for example can change the way html is generated ?

Also it's behind an OR `||` so it just cost nothing if not used...

**Pull request closed without merging**
