### PR TITLE
Corrects first video always autoplay enabled

### PR DESCRIPTION
**Pull request by guiferrpereira**
i believe this fix this [issue](https://github.com/sachinchoolur/lightGallery/issues/382). This problem only happen for first video (vimeo|youtube) it doesn't matter it will always autoplaying.

### CODE REVIEW

**Comment by sachinchoolur** [comment]
Hi @guiferrpereira,
Thank you for the PR. But, I think autoplay should be controlled from settings. Otherwise, if you pass `{autoplay :1}` via settings all the videos will start playing together. 

I'm thinking of adding two more options to the settings

- autoplyFirstVideo - **_default : true - enable/disable autoplay option for the first video_**
- autoplayVideoOnSlide - **_default : false - enable/disable autoplay option on each slide change_**

What do you think ?

**Comment by guiferrpereira** [comment]
it seems awesome :)

**Comment by Gierand** [comment]
Yes, it would be great!

**Comment by cenda** [comment]
Hi @sachinchoolur , sorry for shifting time back :) What about your offer to add `autoplayFirstVideo` param to config object? Is it still in your priority list? It would be great, I'm not able to disable the autoplay in case when only one video on page. Every time when lightbox is displayed, video starts to play.

**Comment by sachinchoolur** [comment]
Hey Guys,
I've added option `autoplyFirstVideo` to manage the autoplay of the first video. Please use the latest version of lg-video.js

@guiferrpereira, Closing the PR. I'll introduce `autoplayVideoOnSlide` if we get more feature request on the same. Thank you so much for your time and effort

**Comment by whitecreek** [comment]
Hi there,
What happenned with _**autoplayVideoOnSlide**_? Was it finally implemented?

Thx in advance

**Comment by valjar** [comment]
I also wish for autoplayVideoOnSlide feature. Was trying to click on play button with JS, but I got error
`Uncaught DOMException: Blocked a frame with origin "http://localhost:8080" from accessing a cross-origin frame` so this feature would be nice! ;) thank you for everything else!

**Comment by johanvdr** [comment]
Hello, I'd really like the autoplayVideoOnSlide feature.

**Pull request closed without merging**
