### PR TITLE
Simple lightbox mode

### PR DESCRIPTION
**Pull request by Grigory90**
Small improvement :)

### CODE REVIEW

**Comment by sachinchoolur** [comment]
Thank you so much for your contribution. 
But i think we don't need an additional option as we can easily do this by setting `selector` to `this`
``` javascript
$('#lightgallery').lightGallery({
    selector: 'this'
});
```

**Comment by Grigory90** [comment]
But if you need to initialize in the page lightbox and gallery, you will need to make two calls to for different selectors. And with my very little option, such problems would not exist.

**Comment by sachinchoolur** [comment]
I would prefer to make two function call with `id` instead of calling it via single `class`.
Inside the lightgallery function it is going through all elements in the dom and assigning lightgallery function to all the elements with the same class. It is a slow process. 
In the case of id, it is supposed to be unique, so the API stops searching after the ID is found in the DOM.
As far as i know using `id` is the preferred method in this scenario. What do you think?
https://github.com/sachinchoolur/lightGallery/blob/master/src/js/lightgallery.js#L1292

**Comment by Grigory90** [comment]
@sachinchoolur Hmm, it looks like you're right, this branch is bad practice :)

**Pull request closed without merging**
