### PR TITLE
Add lightgallery icons in woff2

### PR DESCRIPTION
**Pull request by S1SYPHOS**
Followup to #1030

### CODE REVIEW

**Comment by sachinchoolur** [comment]
Thank you 😊

**Comment by stof** [comment]
@S1SYPHOS too bad that you haven't taken my review into account about the order of declaration. the woff2 support is currently useless, as there is no browser supporting woff2 without support woff. and browsers will use the first supported format. So woff2 must come first, not third.

**Comment by sachinchoolur** [comment]
@stof ,
Thank you for finding time to review the PR. I've already made the changes - https://github.com/sachinchoolur/lightGallery/commit/d01acad0ad5f0a03c618868a7bfdede9f5ca0fb5

**Comment by S1SYPHOS** [comment]
> @S1SYPHOS too bad that you haven't taken my review into account about the order of declaration. the woff2 support is currently useless, as there is no browser supporting woff2 without support woff. and browsers will use the first supported format. So woff2 must come first, not third.

I don't like your tone, but the argument is valid. Thanks!

**Pull request merged**
