### PR TITLE
Features/996 - Language translation aria-label

### PR DESCRIPTION
**Pull request by arnaud-ober**
Test have been done with French language. Obviously we would need to add more languages in the future.

### CODE REVIEW

**Comment by sachinchoolur** [comment]
Thank you for the PR.
This looks really good. But, I think we can make a separate lightGallery plugin for `i18next`. So that people who use their own translation service can just pass the strings via settings, and people who want to use `i18next` can just use this plugin.

Here is the summary of what I have in my mind 
- lightGallery will have an option to pass the strings via settings. lightGallery core will not have any logic related to translation. 
``` js
lightGallery(document.getElementById('lightgallery'),{
    strings: {
        closeGallery: 'Close gallery' ,// users can change this using their service if required
        previousSlide: 'Previous slide
    },
    zoomPluginStrings: {
        viewActualSize: 'View actual size'
    }
})
```
- `i18next` plugin is responsible for passing the translated string to lightGallery. You can take a look at lightgallery [medium-zoom plugin](https://github.com/sachinchoolur/lightGallery/blob/master/src/plugins/mediumZoom/lg-medium-zoom.ts#L28) for reference.

Let me know what do you think.

**Comment by arnaud-ober** [comment]
Hello,

That sounds a good idea to me. I will then change my branch to take in consideration these two scenarios.

**Comment by sachinchoolur** [comment]
Thanks

**Comment by arnaud-ober** [comment]
The strings settings part is done. I still have to make the i18next plugin.

**Comment by sachinchoolur** [comment]
Hey @arnaud-ober,

Thank you so much for making the changes. The next release is majorly for video modules. I think we can include the changes in version 2.2.4 release

**Comment by arnaud-ober** [comment]
@sachinchoolur , I created the plugin. However, I don't know how to resolve the issue we got. I have the impression that the plugin translation is done after the light Gallery is rendered. Which means that the setting is correctly translated, but the aria-label is already rendered with the default string. Do you see a way to init the translation before rendering? Or maybe refresh the gallery?

**Comment by sachinchoolur** [comment]
Really sorry for the delayed response. Yes, this looks like a serious issue. Either delay lightGallery initialization or refresh it once the translation is completed. And practically both of these options are not feasible. 

So I think we might need to drop the idea of creating a lighGallery plugin for translation. lightGallery will just have the option to configure strings. Developers can translate the strings using [i18next](https://www.i18next.com/) or any other similar service and pass the strings to lightGallery. lighGallery can be initialized when the translation is completed as they have full control

What do you think?  If you agree I'll merge the PR ASAP and make the minor changes myself

**Comment by arnaud-ober** [comment]
That was indeed my guess that it would be really hard to make it work. So that works for me to just offer the translation strings. I reverted the last commit which was the i18next plugin. So you can merge the PR and do your changes whenever you're ready! :)

**Comment by sachinchoolur** [comment]
Thank you so much. 
I'm working on a few minor changes. Once that is done, I'll merge the PR.

**Comment by sachinchoolur** [comment]
Hey @arnaud-ober,

The PR has been merged, and it is available in version [2.4.0-beta.0](https://github.com/sachinchoolur/lightGallery/releases/tag/2.4.0-beta.0)

Thank you so much for your time and effort.

**Comment by elvisef** [comment]
> ```js
> lightGallery(document.getElementById('lightgallery'),{
>     strings: {
>         closeGallery: 'Close gallery' ,// users can change this using their service if required
>         previousSlide: 'Previous slide
>     },
>     zoomPluginStrings: {
>         viewActualSize: 'View actual size'
>     }
> })
> ```

Where can I find in the DOCS how to use "strings" to change aria-labels ? I couldn't find it anywhere..

**Comment by sachinchoolur** [comment]
It looks like there are some issues with the autogenerated docs. 

You can find all the possible options below. 

```js

lightGallery(document.getElementById('lightgallery'), {
    strings: {
        closeGallery: 'Close gallery',
        toggleMaximize: 'Toggle maximize',
        previousSlide: 'Previous slide',
        nextSlide: 'Next slide',
        download: 'Download',
        playVideo: 'Play video',
    },
    autoplayPluginStrings: {
        toggleAutoplay: 'Toggle Autoplay'
    },
    commentPluginStrings: {
        toggleComments: 'Toggle Comments'
    },
    fullscreenPluginStrings: {
        toggleFullscreen: 'Toggle Fullscreen'
    },
    rotatePluginStrings: {
        flipVertical: 'Flip vertical',
        flipHorizontal: 'Flip horizontal',
        rotateLeft: 'Rotate left',
        rotateRight: 'Rotate right',
    },
    sharePluginStrings: {
        share: 'Share'
    },
    thumbnailPluginStrings: {
        toggleThumbnails: 'Toggle thumbnails'
    },
    zoomPluginStrings: {
        zoomIn: 'Zoom in',
        zoomOut: 'Zoom out',
        viewActualSize: 'View actual size',
    },
})
```

I'll update the docs

**Pull request merged**
